import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
    
    title:{
      absolute : "title only"
    },
    description: "Generated by create next app",
    
  };

const Aboutlayout = ({ children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
    
  return (
    <div className='bg-slate-600 text-center text-teal-300 p-6 rounded-s-3xl'>
        About layout
      {children}
    </div>
  )
}

export default Aboutlayout
